### ISSUE TITLE
comptime

### ISSUE THREAD

**Issue by newgnart** [sambarnes/noir-by-example#1]
In `comptime` example, you said that 

```rust
// cannot be mutable tho, so this would fail???
let mut bad_var: comptime Field = 3;
```
But looks like mutable is ok, the error is unused variable `bad_var`. using it e.g. `assert(bad_var == 3);` will work

So `comptime Field` can be mutable apparently?

**Comment by sambarnes** [comment]
hmm i thought it errored when i was writing this 🤔 but yeah retried it now and its not erroring

the official docs say that it should fail too:
https://noir-lang.org/language_concepts/mutability/#comptime-values

---

might be better to open an issue in the main noir repo if you're up for it @trangnv!

**Comment by sambarnes** [comment]
i've updated the example such that the unused variable warning won't show -- instead, the failure should show once the bug is patched in noir itself

https://github.com/sambarnes/noir-by-example/commit/225c7b31a84083c8ddd5522fdb3007500a0d1f9f

**Comment by newgnart** [comment]
Sure will take a look and file one on noir repo if necessary

**Comment by sambarnes** [comment]
ah rad -- closing :)

![image](https://github.com/sambarnes/noir-by-example/assets/1211977/c2e4abc4-a095-4c51-9a5c-06205f810d5f)
